"use client";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

import Header from "@/component/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: 0,
      },
    },
  });

  return (
    <html lang="en">
      <head>
        <meta name="description" content="Polifix Logo" />
        <meta name="google-site-verification" content="j5W3OlHrfhQimQnlwsl89etr58MJd_u8s3rgrpJ5Sg8" />
        <title>
          PoliFIX Consults | Policy Consulting for Sustainable Governance
        </title>
        <meta
          name="description"
          content="PoliFIX provides expert policy consulting and advisory services, driving sustainable development through research and data analytics. Explore our insights on governance, civic engagement, and digital reform."
        />
        <link rel="icon" href="/vercel.svg" />
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <div className="container">
            <Header />
            {children}
            <footer className="footer">
              <div className="foot-left">
                <img
                  src="/civicLogo.svg"
                  width="200px"
                  alt="Civic Policy Archive Logo"
                />
                <nav className="foot_navs">
                  <a href="#">About Us</a>
                  <a href="#">Blog</a>
                  <a href="#">Press Release</a>
                  <a href="#">Contact Us</a>
                </nav>
                <p>PoliFIX &copy; 2025</p>
              </div>
              <div id="contact-us" className="podcastIcons">
                <h3>CONTACT US </h3>
                <a href="https://www.youtube.com/@TheCivicPolicyArchive">
                  <img width="24px" src="/youtubeBlack.svg" alt="YouTube" />
                  @SENDPOLIFIX
                </a>
                <a href="https://www.instagram.com/sendpolifix?igsh=MW9mcWowaWY4Njd4dw%3D%3D&utm_source=qr">
                  <img width="24px" src="/instagramBlack.svg" alt="Instagram" />
                  @SENDPOLIFIX
                </a>
                <a href="https://x.com/sendpolifix?s=11">
                  <img width="24px" src="/twitterBlack.svg" alt="Twitter" />
                  @SENDPOLIFIX
                </a>
                <a href="">
                  <img width="24px" src="/mail.svg" alt="Mail" />
                  admin@polifixconsults.com
                </a>
              </div>
            </footer>
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
